### PR TITLE
Added support for initializationOptions

### PR DESCRIPTION
**Pull request by DanielViberg**
Solves this issue: https://github.com/yegappan/lsp/issues/291

### CODE REVIEW

**Comment by normen** [comment]
Cool, thanks!

**Comment by normen** [comment]
Err sorry but this breaks pretty much all of my language servers.. I guess I will have to revert unless you have some idea about this.

Edit: Wait, I think its actually the configuration of some of my servers (not set up though `vim-lsp-settings`)

**Comment by normen** [comment]
Yeah, 4get it, all are working fine. Thanks again for the fix!

**Comment by DanielViberg** [comment]
Might be wise to add a conditional to verify the existence of initialization_options, might push update in future.

**Pull request merged**
